### ISSUE TITLE
[1.12.2] Baby Chickens Become Adults

### ISSUE THREAD

**Issue by EmosewaPixel** [timrwood/roost#11]
Baby Chickens picked up with the Chicken Catcher turn into adults when placed back down.

**Comment by timrwood** [comment]
Ah, yeah, I'll have to think about how to solve this one...

**Comment by EmosewaGamer** [comment]
Add "Time till grown:" to the bottom of the tooltip, make it be equal to the time the chicken had left before picked up, make chickens with in unusable in your machines.and maybe integrate it into the Breeder. :P

**Comment by timrwood** [comment]
Adding "Time till grown" for each chicken item will make them unstackable. I think I'll just prevent baby chickens from being caught with the Catcher for now.

**Comment by timrwood** [comment]
I added an alpha release file to CurseForge, if everything looks good, I'll promote it to the official 1.3.0 release.

https://minecraft.curseforge.com/projects/roost/files/2635449

**Comment by timrwood** [comment]
This is addressed in [1.3.0](https://minecraft.curseforge.com/projects/roost/files/2635449)
