### ISSUE TITLE
[Suggestion] Configurable Breeding Speed

### ISSUE THREAD

**Issue by EmosewaGamer** [timrwood/roost#12]
Could you please make the Chicken Breeder have a configurable speed?

**Comment by timrwood** [comment]
Do you want it to be faster or slower?

A breeder with 1 vanilla chicken in each parent slot will produce a child every 5-10 minutes. That number is shorter the more chickens you have in each slot. With 2 in each slot: 2.5-5 minutes, with 5 in each slot: 1-2 minutes, with 16 in each: 18-36 seconds.

With modded chickens, the growth will also increase the speed. 1 chicken with growth:10 will produce children as fast as 10 chickens with growth:1.

**Comment by EmosewaGamer** [comment]
Oh? Every time I tested it with More Chickens I got a time of 2min 45s. Nvm then.

**Comment by timrwood** [comment]
I think higher tier chickens are also a little slower, so that may be factoring in as well.

**Comment by EmosewaGamer** [comment]
Oh, well the first Chickens I tried were 3/3/3. That probably explains it.
