### ISSUE TITLE
Roosts Work After They Are Full

### ISSUE THREAD

**Issue by EmosewaPixel** [timrwood/roost#14]
Roosts continue working after they are full which above all else, cause massive tps lag on servers.

**Comment by timrwood** [comment]
Good point, I'll take a look at this

**Comment by generrosity** [comment]
+1 - interested in Roosts specifically for this kinda thing. Are there beta builds out there too?

**Comment by timrwood** [comment]
I added an alpha release file to CurseForge, if everything looks good, I'll promote it to the official 1.3.0 release.

https://minecraft.curseforge.com/projects/roost/files/2635449

**Comment by timrwood** [comment]
This is addressed in [1.3.0](https://minecraft.curseforge.com/projects/roost/files/2635449)
