### ISSUE TITLE
[Suggestion] Breeders active/idle visuals

### ISSUE THREAD

**Issue by Nagshell** [timrwood/roost#15]
I'm not sure if this is viable in terms of efficiency, but I'd love to see when my Breeders are actively working (chickens + at least 2 seeds are inside).

Right now there is visual effect after finishing each breed, which let's you know when it's done, but after that effect disappears it's not possible to distinguish between breeders.

Main reason behind changing that is improving chickens to 10/10/10 takes quite some time, and personally I'm doing it by placing 2 chickens and 4 seeds to breed 2 better chickens, and repeat the process. When doing it with multiple species at the same time it's very time consuming to check all breeders if they are done.

**Comment by efinder2** [comment]
Better do this when the Output is full and no breed could be done

**Comment by timrwood** [comment]
I added an alpha release file to CurseForge, if everything looks good, I'll promote it to the official 1.3.0 release.

https://minecraft.curseforge.com/projects/roost/files/2635449

**Comment by timrwood** [comment]
This is added in [1.3.0](https://minecraft.curseforge.com/projects/roost/files/2635449)
