### ISSUE TITLE
[Suggestion] Cross breeding leveled chickens

### ISSUE THREAD

**Issue by UncertifiedDevice** [timrwood/roost#16]
Currently successfully cross breeding two maxxed chickens only gives a regular chicken with no stats. I think it would be best if each stat of any two chickens being crossbred was averaged and then halved to give the stats of the child chicken.
Example:
Two chickens, Log chicken with stats 4/2/4, Flint chicken with stats 8/6/8. The average of each stat makes 6/4/6, half of each stat makes 3/2/3 resulting in a coal chicken with stats 3/2/3.

**Comment by EmosewaGamer** [comment]
Probably because that's how breeding Chickens in the world works and it's what balances the mod.

**Comment by timrwood** [comment]
@EmosewaGamer, correct, the breeder uses whatever logic normal chicken breeding uses.

See https://github.com/setycz/ChickensMod/issues/76 and https://github.com/GenDeathrow/Hatchery/issues/69
