### ISSUE TITLE
Add Support For New More Chickens Chickens

### ISSUE THREAD

**Issue by EmosewaPixel** [timrwood/roost#18]
More Chickens updated with a few new Chickens to add support for Tech Reborn. You should probably add support for them (i.e. add textures for them).

**Comment by timrwood** [comment]
I added an alpha release file to CurseForge, if everything looks good, I'll promote it to the official 1.3.0 release.

https://minecraft.curseforge.com/projects/roost/files/2635449

**Comment by timrwood** [comment]
This is fixed in [1.3.0](https://minecraft.curseforge.com/projects/roost/files/2635449)
