### ISSUE TITLE
Issue with Roost Percentage during breeding

### ISSUE THREAD

**Issue by BlueVal** [timrwood/roost#20]
Heyo there, 

I wanted to mention this issue : it happens on my 1.12.2 when anyone uses the breeding.
Is there any known issue with this with any mod or is this something happening in roost ?

Placing 2 chickens in the breeder will make it go reverse, at one point this can change to the other example where it will count down again for some reason.

![roost_timer](https://user-images.githubusercontent.com/36119033/35837597-e7a525c0-0ade-11e8-91b4-a4ce5ce735db.png)
![roost_reverse_breeding_timer](https://user-images.githubusercontent.com/36119033/35837600-e8d8505c-0ade-11e8-9ff3-1a87284adb34.png)

**Comment by BlueVal** [comment]
Nevermind, bit tired, duplicate of #13 sorry :P

**Comment by timrwood** [comment]
This is fixed in [1.3.0](https://minecraft.curseforge.com/projects/roost/files/2635449)
