### ISSUE TITLE
Crazy numbers and +/- with graphical glitches when changing lay coefficient in Chickens mod

### ISSUE THREAD

**Issue by TheRealDadbeard** [timrwood/roost#26]
Title

Screenshot: https://imgur.com/mUDJ6kk

Coefficient is on 2.0

**Comment by JayJay1989** [comment]
Likely some bug, in the GUI some strange percentage, on waila the right one
GUI: https://imgur.com/a/XAVbdNt
waila: https://imgur.com/a/59OBban

**Comment by timrwood** [comment]
This is fixed in [1.3.0](https://minecraft.curseforge.com/projects/roost/files/2635449)
