### ISSUE TITLE
Config?

### ISSUE THREAD

**Issue by DemonfangArun** [timrwood/roost#39]
I cannot seem to locate a configuration file for this mod, and I need to turn down the speed of both breeding and how fast items are produced because it's causing a major balancing issue. If someone could direct me on how to configure breeders and roosts it would be much appreciated.

**Comment by timrwood** [comment]
I think you can use the config for the chickens mod for most of this, as Roost uses that data for calculating breeding times.

**Comment by timrwood** [comment]
Also, https://github.com/timrwood/roost/pull/36 added this feature, and it will be included in the 1.3.0 release

**Comment by JLewis1309** [comment]
any chance of adding a config option to change Chicken Stack sizes to? as soon as i learned that stacking chickens in a breeder made it go faster i wanted to see how insane it would be if you could have 64 Chickens breeding with 64 Chickens instead of 16 + 16 lol

**Comment by DAmNRelentless** [comment]
When will the 1.3.0 be released? It really needs all the updates you've done so far.

**Comment by timrwood** [comment]
The only blocker right now is doing a full QA pass. Maybe I'll upload an alpha release to curseforge and other people can help with QA?

**Comment by DAmNRelentless** [comment]
What's meant by QA? I help wherever I can as long as it helps the progress. The minus percentages (sometimes like 100k) are just annoying.

**Comment by DemonfangArun** [comment]
> 
> 
> What's meant by QA? I help wherever I can as long as it helps the progress. The minus percentages (sometimes like 100k) are just annoying.

Quality Assurance, in this instance debugging.

**Comment by timrwood** [comment]
This was added in [1.3.0](https://minecraft.curseforge.com/projects/roost/files/2635449)
