### ISSUE TITLE
Typo: Diamantine Chicken should be called Diamatine

### ISSUE THREAD

**Issue by aaronhowser1** [timrwood/roost#51]
![image](https://user-images.githubusercontent.com/15698722/50217970-f89f4d00-034f-11e9-9a89-2a83cfcb0d5d.png)

**Comment by timrwood** [comment]
This name comes from the [MoreChickens](https://github.com/GenDeathrow/MoreChickens/blob/master/src/main/resources/assets/morechickens/lang/en_US.lang#L104) mod, and should be changed there.
