### ISSUE TITLE
Classloading crash without Chickens [2.0.7]

### ISSUE THREAD

**Issue by duely** [timrwood/roost#62]
https://paste.dimdev.org/ufudujuhar.mccrash

Apologies for the VanillaFix crashlog, but it appears that the most recent update is somehow not behind a "don't do this if Chickens isn't installed" wall, as it's attempting to classload something that doesn't exist.

Good luck with figuring it out! Especially as I see the changelog spoke about CraftTweaker integration.

**Comment by codewarrior0** [comment]
While this is a valid issue (because previous versions worked without Chickens), the CT integration in the changelog is specifically for Chickens' own ContentTweaker integration, so don't get your hopes up.

**Comment by duely** [comment]
That's fine, I was just running off the fact that it still says "optional dependency" for Chickens. I don't care about CraftTweaker interaction, I just understand that getting an optional dependency to work with CraftTweaker can be confusing.

**Comment by xAlicatt** [comment]
Was coming to report this. If you are going to require Chickens going forward, it needs to be set up as a dependency, and it would be nice if you would fork it and have two versions. Not every pack maker wants to allow infinite farmable resources that Chickens has, but enjoys the features of Roost for vanilla chicken farming.

**Comment by codewarrior0** [comment]
Fixed in 2.0.8
