### ISSUE TITLE
Broken Textures in 6.1.0

### ISSUE THREAD

**Issue by katubug** [timrwood/roost#64]
Hi there! I just updated to the most recent update, and some of the chickens are non-textured. They are:

- Conductive Iron
- Energetic Alloy
- Rich Slag
- Basalz Rod
- Blood
- Blue Slime
- Darksteel
- Electrical Steel
- Redstone Alloy
- Blitz Rod
- Magma Slime
- Pig Iron
- Pulsating Iron
- Purple Slime
- Vibrant Alloy
- Blizz Rod
- Knight Slime

![2019-04-18_20 49 35](https://user-images.githubusercontent.com/20935286/56400855-aac22500-621b-11e9-99e7-5e97d62ce2f9.png)

**Comment by katubug** [comment]
Also, shadows in the roosts are weird now.

![2019-04-18_21 21 40](https://user-images.githubusercontent.com/20935286/56401744-0ee6e800-6220-11e9-8ed8-1a757b75b133.png)

**Comment by codewarrior0** [comment]
Fixed in 2.0.9
