### ISSUE TITLE
[1.12.2] Roost Chicken In Tabs

### ISSUE THREAD

**Issue by BuilderDan** [timrwood/roost#8]
That little chicken at the end of the GUI seems to be appearing in every single creative tab:

![image](https://user-images.githubusercontent.com/19805371/32930084-4e54b104-cb11-11e7-8080-33f300e254ba.png)

![image](https://user-images.githubusercontent.com/19805371/32930097-5e32b8e6-cb11-11e7-8ab3-e7ab1d54aec8.png)

Would love a fix for this so I can use this mod with the newly updated Chickens mod.

**Comment by timrwood** [comment]
https://github.com/timrwood/roost/pull/10 should address this, I'll release it shortly, once I have had time to go through my QA checklist
