### ISSUE TITLE
Chicken Catcher and More Chickens mod

### ISSUE THREAD

**Issue by ntn6371** [timrwood/roost#9]
If you use chicken catcher on a MoreChickens mod chicken it turns back to a regular chicken. :(

**Comment by AllieWade** [comment]
Same issue here.

Minecraft 1.12.2
Forge 14.23.0.2550
Roost 1.12-1.1.0
Chickens 6.0.2
More Chickens 1.12.2-3.0.0

**Comment by timrwood** [comment]
https://github.com/timrwood/roost/pull/10 should address this, I'll release it shortly, once I have had time to go through my QA checklist

**Comment by AllieWade** [comment]
Sweet, thank you!

**Comment by ntn6371** [comment]
great work much love <3

**Comment by timrwood** [comment]
This is released here: https://minecraft.curseforge.com/projects/roost/files/2504280
